Deathtest
java-park-mail-ru/card-game-09-2016 pull request #1
Opened 2016-10-03 23:14 UTC by Alexandr030291

А здесь сами заводим деплой для командной, просто на фронте за нас это делал ментор а мы заводили только для своего форка

2016-10-03 23:21 UTC, KSolovyev commented
По спеке: вы не получаете куку в теле ответа. Вам ее устанавливает сервер заголовком. Ее не должно быть в API. Вы можете отметить некоторые методы, как требующие авторизации
В общем убирайте ее отовсюду. Посмотрите как сделано в
http://petstore.swagger.io/#!/user/updateUser
Там тоже есть регистрация и авторизация

2016-10-04 21:44 UTC, Alexandr030291 commented
Проблема возникла сервер не разворачивается на хероку

2016-10-04 21:48 UTC, KSolovyev requested changes

2016-10-04 21:48 UTC, KSolovyev commented on .gitignore
> +# Mongo Explorer plugin:
Не нужно нет у нас его

2016-10-04 21:48 UTC, KSolovyev commented on .gitignore
> +## File-based project format:
Этого тоже нет

2016-10-04 21:48 UTC, KSolovyev commented on .gitignore
> +# Mobile Tools for Java (J2ME)
j2me тем более

2016-10-04 23:10 UTC, KSolovyev commented
Если не разворачивается сервер, то пишите в чатик, будем исследовать

2016-10-04 23:12 UTC, KSolovyev commented
Но сходу могу сказать, что у вас класс main не указан в pom.xml

2016-10-05 16:42 UTC, KSolovyev requested changes

2016-10-05 16:42 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("{Одно из полей пусто}");
По поводу русского текста всем пишу. В API не надо вставлять текст, потому что вы всегда должны подразумевать локализацию вашего приложения. Локализацию удобнее всего использовать клиентскую(иначе придется использовать и клиентскую и серверную), поэтому в ответ вы должны послать либо код ошибки, либо ключ клиентской локализации(по которому из специального словарика вставляется текст на нужном языке). Кроме того у вас не валидный json

2016-10-05 16:42 UTC, KSolovyev commented on tp_java_new.xml
> +<inspections version="1.0">
этот файл надо удалить, вы его уже импортировали

2016-10-05 16:42 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +                accountService.removeUser(temp.getLogin());
Вы не чистите сессию, при этом метод checkAuth смотрит только в SessionService. Если удалить пользователя, сервер будет отвечать, что он залогинен, но пользователя при этом не найдет

2016-10-05 16:42 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +                        accountService.changeUser(sessionService.returnLogin(sessionId.getId()), login, password, email);
после смены имени, мы не сможем найти пользователя по имени, тк в SessionService имя останется старым

2016-10-05 16:42 UTC, KSolovyev commented on .gitignore
> +## File-based project format:
не нужно

2016-10-05 23:04 UTC, KSolovyev requested changes

2016-10-05 23:04 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +    public ResponseEntity getInfo(@PathVariable("id") int id, HttpSession sessionId) {
а id тогда зачем?

2016-10-05 23:04 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +        if (sessionService.checkExists(sessionId.getId())) {
в таких местах, чтобы уменьшить вложенность конструкций, надо писать
```
if (!sessionService.checkExists(sessionId.getId())) {
    return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("{}");
}
```

2016-10-05 23:33 UTC, devil1001 commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +    public ResponseEntity getInfo(@PathVariable("id") int id, HttpSession sessionId) {
ой, тут ошибся, в accountService.getUser просто id надо передать

2016-10-08 23:04 UTC, KSolovyev commented
Вроде все поправили. Вы еще что-то хотите добавить в пул-реквест?

2016-10-09 09:59 UTC, Alexandr030291 commented
поправим сегодня замечания которые дали на рк, и вопрос по деплою на хероку мы сами его с командной папки делаем себе еще, или вы заводите контрольный деплой?

2016-10-09 10:09 UTC, KSolovyev commented
Вы сами делаете

2016-10-13 17:08 UTC, Alexandr030291 commented
То что хотели дописали
https://stackdouble.herokuapp.com/ здесь можно уже попробовать зарегистрироваться и войти, роутеры на фронте еще не до конца настроены поэтому там могут возникать некоторый ошибки с навигацией, и на стороне фронта немного не правильно обрабатывается существующий пользователь, но это уже проблемы с фронтом, времени не хватает

2016-10-13 19:10 UTC, KSolovyev approved these changes

2016-10-13 19:11 UTC, merged

2016-10-13 19:12 UTC, KSolovyev commented
для полной интеграции нужен запрос из фронта к бэку, который требует куку. Например,выведите на главной странице фразу привет %username%, если пользователь уже залогинен